
logging:
  level:
    root: info
  config: classpath:logback.xml

jwt:
  signing:
    key: 53d2a25eb85f8cc5452aebbf05ff7f1bc280bd26e6a3a805cfce346986562e34
  expire-days:
    access-token: 7
    refresh-token: 365

spring:
  application:
    name: jungle-book-api
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
    redis:
      host: localhost
      port: 6379
  datasource:
    hikari:
      main:
        pool-name: contents-hikari-pool
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/junglebook?useSSL=false
        username: jgb
        password: jgb123!@#
        connection-timeout: 30000
        minimum-idle: 2
        maximum-pool-size: 5
        idle-timeout: 0
        max-lifetime: 1800000
        auto-commit: false
        connection-test-query: SELECT 1
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      hbm2ddl.auto: none
      enable_lazy_load_no_trans: false
      implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      default_batch_fetch_size: 100
