services:
  database:
    container_name: junglebook-mysql
    image: mysql:8.0.29-oracle
    cap_add:
      - SYS_NICE
    restart: always
    volumes:
      - ./datadir/mysql:/var/lib/mysql
      - ./schema/init.sql/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: junglebook
      MYSQL_USER: junglebook
      MYSQL_PASSWORD: "junglebook123!@#"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default_time_zone=+09:00
      - --explicit_defaults_for_timestamp
  redis:
    container_name: junglebook-redis
    image: redis:7.0.12
    ports:
      - "16379:6379"
    volumes:
      - ./datadir/redis:/data
    labels:
      - "mode=standalone"